openapi: 3.0.3
info:
  title: login API
  description: API endpoints to login and register
  version: 1.0.0
servers:
  - url: '/auth'
paths:
  /login:
    post:
      tags:
        - Login
      summary: Login using credentials
      operationId: controllers.login.process_login_request
      requestBody:
        $ref: '#/components/requestBodies/credentials'
      responses:
        200:
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/responses/accessToken'
  /register:
    post:
      tags:
        - Register
      summary: Register a new user
      operationId: controllers.login.process_registration_request
      requestBody:
        $ref: '#/components/requestBodies/employeeInformation'
      responses:
        200:
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: '#/components/responses/registrationSuccessful'
components:
  requestBodies:
    credentials:
      description: JSON object containing username and password
      content:
        'application/json':
          schema:
            type: object
            properties:
              username:
                type: string
                description: Username of ths user
              password:
                type: string
                description: Password of the user
            required:
              - username
              - password
    employeeInformation:
      description: JSON object containing username and password
      content:
        'application/json':
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee
              username:
                type: string
                description: Username of ths employee
              password:
                type: string
                description: Password of the employee
              role:
                type: string
                description: Role of the employee
            required:
              - name
              - contact_number
              - username
              - password
              - role
  responses:
    accessToken:
      description: JSON object containing the access token
      content:
        'application/json':
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: Access token of the user
            required:
              - access_token
    registrationSuccessful:
      description: JSON object containing the newly created employee
      content:
        'application/json':
          schema:
            type: object
            properties:
              Id:
                type: integer
                description: Id of the newly created employee
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee
              username:
                type: string
                description: Username of ths employee
              role:
                type: string
                description: Role of the employee
            required:
              - name
              - contact_number
              - username
              - role