swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /operations

paths:
  /employees:
    get:
      operationId: controllers.employees.read_all
      tags:
        - Employees
      summary: Read the entire set of employees
      description: Read the entire set of employees, sorted by name
      responses:
        200:
          description: Successfully read employees set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the employee
                name:
                  type: string
                  description: Id of the employee
                contact_number:
                  type: integer
                  description: Id of the employee
                email:
                  type: string
                  description: Email of the employee
                orders_served:
                  type: array
                  items:
                    properties:
                      id:
                        type: string
                        description: Id of the order
                      order_time:
                        type: string
                        description: Creation/Update timestamp of the order
                      status:
                        type: string
                        description: state of the order (Ready, Preparing, or Cancelled)
                      customer_id:
                        type: integer
                        description: Id of customer
    post:
      operationId: controllers.employees.create
      tags:
        - Employee
      summary: Create an employee
      description: Create a new employee
      parameters:
        - name: employee
          in: body
          description: employee to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of employee to create
      responses:
        201:
          description: Successfully created an employee
          schema:
            properties:
              id:
                type: string
                description: Id of the employee
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee

  /employees/{employee_id}:
    get:
      operationId: controllers.employees.read_one
      tags:
        - Employees
      summary: Read one employee
      description: Read one employee
      parameters:
        - name: employee_id
          in: path
          description: Id of the employee to get
          type: integer
          required: true
      responses:
        200:
          description: Successfully read employee from db Employee table
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the employee
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee
              orders_served:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: Id of the order
                    order_time:
                      type: string
                      description: Creation/Update timestamp of the order
                    status:
                      type: string
                      description: state of the order (Ready, Preparing, or Cancelled)
                    customer_id:
                      type: integer
                      description: Id of customer
    put:
      operationId: controllers.employees.update
      tags:
        - Employees
      summary: Update an employee
      description: Update an employee
      parameters:
        - name: employee_id
          in: path
          description: Id of the employee to update
          type: integer
          required: true
        - name: employee
          in: body
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee
      responses:
        200:
          description: Successfully updated employee
          schema:
            properties:
              id:
                type: string
                description: Id of the employee
              name:
                type: string
                description: Name of the employee
              contact_number:
                type: integer
                description: Contact number of the employee
              email:
                type: string
                description: Email of the employee
    delete:
      operationId: controllers.employees.delete
      tags:
        - Employee
      summary: Delete an employee from the database
      description: Delete an employee
      parameters:
        - name: employee_id
          in: path
          type: integer
          description: Id of the employee to delete
          required: true
      responses:
        200:
          description: Successfully deleted an employee

  /items:
    get:
      operationId: controllers.items.read_all
      tags:
        - Items
      summary: Read the entire set of items
      description: Read the entire set of items, sorted by name
      responses:
        200:
          description: Successfully read items set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the item
                name:
                  type: string
                  description: Name of the item
                ingredients:
                  type: string
                  description: Ingredients of item
                price:
                  type: string
                  description: Price of item
    post:
      operationId: controllers.items.create
      tags:
        - Items
      summary: Create an item
      description: Create a new item
      parameters:
        - name: item
          in: body
          description: item to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the item
              ingredients:
                type: string
                description: Ingredients of item
              price:
                type: string
                description: Price of item
      responses:
        201:
          description: Successfully created an item
          schema:
            properties:
              id:
                type: string
                description: Id of the item
              name:
                type: string
                description: Name of the item
              ingredients:
                type: string
                description: Ingredients of item
              price:
                type: string
                description: Price of item
  /items/{item_id}:
    get:
      operationId: controllers.items.read_one
      tags:
        - Items
      summary: Read one item
      description: Read one item
      parameters:
        - name: item_id
          in: path
          description: Id of the item to get
          type: integer
          required: true
      responses:
        200:
          description: Successfully read item from db Item table
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the item
              name:
                type: string
                description: Name of the item
              ingredients:
                type: string
                description: Ingredients of item
              price:
                type: string
                description: Price of item
    put:
      operationId: controllers.items.update
      tags:
        - Items
      summary: Update an item
      description: Update an item
      parameters:
        - name: item_id
          in: path
          description: Id of the item to update
          type: integer
          required: true
        - name: item
          in: body
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the item
              ingredients:
                type: string
                description: Ingredients of item
              price:
                type: string
                description: Price of item
      responses:
        200:
          description: Successfully updated item
          schema:
            properties:
              name:
                type: string
                description: Name of the item
              ingredients:
                type: string
                description: Ingredients of item
              price:
                type: string
                description: Price of item
    delete:
      operationId: controllers.items.delete
      tags:
        - Item
      summary: Delete an item from the database
      description: Delete an item
      parameters:
        - name: item_id
          in: path
          type: integer
          description: Id of the item to delete
          required: true
      responses:
        200:
          description: Successfully deleted an item