swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /shop

# Paths supported by the server application
paths:
  /orders:
    get:
      operationId: controllers.orders.read_all
      tags:
        - Orders
      summary: Read the entire set of orders
      description: Read the entire set of orders, sorted by last name
      responses:
        200:
          description: Successfully read orders set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the order
                customer_id:
                  type: string
                  description: Id of the customer
                employee_id:
                  type: string
                  description: Id of the employee
                order_time:
                  type: string
                  description: Creation/Update timestamp of the order
                status:
                  type: string
                  description: state of the order (Ready, Preparing, or Cancelled)
                items_ordered:
                  type: object
                  items:
                    properties:
                      id:
                        type: string
                        description: Id of the order item
                      name:
                        type: string
                        description: Name of the order item
    post:
      operationId: controllers.orders.create
      tags:
        - Order
      summary: Create an order
      description: Create a new order
      parameters:
        - name: order
          in: body
          description: Order to create
          required: True
          schema:
            type: object
            properties:
              customer_name:
                type: string
                description: Name of the Customer
              customer_contact_number:
                type: integer
                description: Contact number of the customer
              employee_contact_number:
                type: integer
                description: Contact number of the employee
              items_ordered:
                type: object
                items:
                  properties:
                    name:
                      type: string
                      description: Name of the order item
                    quantity:
                      type: number
                      description: quantity of the item
                    customer_notes:
                      type: string
                      description: notes of the customer
      responses:
        201:
          description: Successfully created an order
          schema:
            properties:
              id:
                type: string
                description: Id of the order
              customer_id:
                type: string
                description: Id of the customer
              employee_id:
                type: string
                description: Id of the employee
              order_time:
                type: string
                description: Creation/Update timestamp of the order
              status:
                type: string
                description: state of the order (Ready, Preparing, or Cancelled)
              items_ordered:
                type: object
                items:
                  properties:
                    name:
                      type: string
                      description: Name of the order item
                    quantity:
                      type: number
                      description: quantity of the item
                    customer_notes:
                      type: string
                      description: notes of the customer
  /orders/{order_id}:
    get:
      operationId: controllers.orders.read_one
      tags:
        - Orders
      summary: Read one order
      description: Read one order
      parameters:
        - name: order_id
          in: path
          description: Id of the order to get
          type: integer
          required: true
      responses:
        200:
          description: Successfully read order from the database orders table
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the order
              customer_id:
                type: string
                description: Id of the customer
              employee_id:
                type: string
                description: Id of the employee
              order_time:
                type: string
                description: Creation/Update timestamp of the order
              status:
                type: string
                description: state of the order (Ready, Preparing, or Cancelled)
              items_ordered:
                type: object
                items:
                  properties:
                    name:
                      type: string
                      description: Name of the order item
                    quantity:
                      type: number
                      description: quantity of the item
                    customer_notes:
                      type: string
                      description: notes of the customer
    put:
      operationId: controllers.orders.update
      tags:
        - Orders
      summary: Update an order
      description: Update an order
      parameters:
        - name: order_id
          in: path
          description: Id the order to update
          type: integer
          required: true
        - name: order
          in: body
          schema:
            type: object
            properties:
              status:
                type: string
                description: state of the order (Ready, Preparing, or Cancelled)

      responses:
        200:
          description: Successfully updated order
          schema:
            properties:
              id:
                type: string
                description: Id of the order
              customer_id:
                type: string
                description: Id of the customer
              employee_id:
                type: string
                description: Id of the employee
              order_time:
                type: string
                description: Creation/Update timestamp of the order
              status:
                type: string
                description: state of the order (Ready, Preparing, or Cancelled)
              items_ordered:
                type: object
                items:
                  properties:
                    name:
                      type: string
                      description: Name of the order item
                    quantity:
                      type: number
                      description: quantity of the item
                    customer_notes:
                      type: string
                      description: notes of the customer
    delete:
      operationId: controllers.orders.delete
      tags:
        - Order
      summary: Delete an order from the database
      description: Delete an order
      parameters:
        - name: order_id
          in: path
          type: integer
          description: Id of the order to delete
          required: true
      responses:
        200:
          description: Successfully deleted an order
  /customers:
    get:
      operationId: controllers.customers.read_all
      tags:
        - Customers
      summary: Read the entire set of customers
      description: Read the entire set of customers, sorted by name
      responses:
        200:
          description: Successfully read customers set operation
          schema:
            type: array
            items:
              properties:
                id:
                  type: string
                  description: Id of the order
                name:
                  type: string
                  description: Id of the customer
                contact_number:
                  type: integer
                  description: Id of the employee
                orders:
                  type: array
                  items:
                    properties:
                      id:
                        type: string
                        description: Id of the order
    post:
      operationId: controllers.customers.create
      tags:
        - Customer
      summary: Create a customer
      description: Create a new customer
      parameters:
        - name: customer
          in: body
          description: Customer to create
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the Customer
              contact_number:
                type: integer
                description: Contact number of the customer
      responses:
        201:
          description: Successfully created a customer
          schema:
            properties:
              id:
                type: string
                description: Id of the customer
              name:
                type: string
                description: Name of the customer
              contact_number:
                type: integer
                description: Contact number of the customer
              orders:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: Id of the order

  /customers/{customer_id}:
    get:
      operationId: controllers.customers.read_one
      tags:
        - Customers
      summary: Read one customer
      description: Read one customer
      parameters:
        - name: customer_id
          in: path
          description: Id of the customer to get
          type: integer
          required: true
      responses:
        200:
          description: Successfully read customer from db Customer table
          schema:
            type: object
            properties:
              id:
                type: string
                description: Id of the customer
              name:
                type: string
                description: Name of the customer
              contact_number:
                type: integer
                description: Contact number of the customer\
              orders:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: Id of the order
    put:
      operationId: controllers.customers.update
      tags:
        - Customers
      summary: Update a customer
      description: Update a customer
      parameters:
        - name: customer_id
          in: path
          description: Id of the customer to update
          type: integer
          required: true
        - name: customer
          in: body
          required: True
          schema:
            type: object
            properties:
              name:
                type: string
                description: Name of the customer
              contact_number:
                type: integer
                description: Contact number of the customer
      responses:
        200:
          description: Successfully updated customer
          schema:
            properties:
              id:
                type: string
                description: Id of the customer
              name:
                type: string
                description: Name of the customer
              contact_number:
                type: integer
                description: Contact number of the customer\
              orders:
                type: array
                items:
                  properties:
                    id:
                      type: string
                      description: Id of the order
    delete:
      operationId: controllers.customers.delete
      tags:
        - Customer
      summary: Delete a customer from the database
      description: Delete a customer
      parameters:
        - name: customer_id
          in: path
          type: integer
          description: Id of the customer to delete
          required: true
      responses:
        200:
          description: Successfully deleted a customer

  /orders/{order_id}/items:
    put:
      operationId: controllers.orders.update_items
      tags:
        - OrderItems
      summary: Update an order item
      description: Update an order item
      parameters:
        - name: order_id
          in: path
          description: Id the order to update
          type: integer
          required: true
        - name: order_items
          in: body
          schema:
            type: array
            properties:
              order_id:
                type: integer
                description: Id of the order
              item_id:
                type: integer
                description: Id of the item
              quantity:
                type: integer
                description: Quantity of the item
              customer_notes:
                type: string
                description: Notes of the customer on the item ordered
      responses:
        200:
          description: Successfully updated order
          schema:
            properties:
              id:
                type: string
                description: Id of the order
              customer_id:
                type: string
                description: Id of the customer
              employee_id:
                type: string
                description: Id of the employee
              order_time:
                type: string
                description: Creation/Update timestamp of the order
              status:
                type: string
                description: state of the order (Ready, Preparing, or Cancelled)
              items_ordered:
                type: object
                items:
                  properties:
                    name:
                      type: string
                      description: Name of the order item
                    quantity:
                      type: number
                      description: quantity of the item
                    customer_notes:
                      type: string
                      description: notes of the customer
